FROM ruby:2.6.5
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client
COPY . /app

WORKDIR /app
RUN bundle install
RUN rake db:create
RUN rake db:migrate
RUN rake db:seed

ENTRYPOINT ["rails", "s", "-b", "0.0.0.0"]
